# Use the official Nginx image
FROM nginx:alpine

# Copy website files to nginx default directory
COPY index.html /usr/share/nginx/html/index.html

# Expose port 80 to server the website
EXPOSE 80

# Run Nginx in the foreground 
CMD ["nginx", "-g", "daemon off;"] 